### ISSUE TITLE
extendedTimeout, doesn't apply exiting class to component.

### ISSUE THREAD

**Issue by alexanderjeurissen** [poteto/ember-cli-flash#117]
I'm in the process of migrating to ember-cli, using ember-cli-rails.

I wrote two components, one `flash-queue` which renders a `flash-message` component for each flash message object.

Those components work as expected and flash messages are shown. The source code of my  two components and there templates can be seen below.

**flash-queue component:**
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['FlashQueue']
});
```

```html
<div>
  {{#each flashMessages.queue as |flash|}}
    {{flash-message flash=flash}}
  {{/each}}
</div>
```

**flash-message component:**
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['flash-message'],
  classNameBindings: 'flashType',
  flashType: Ember.computed('flash', function() {
    return `is-${this.get('flash.type')}`;
  }),

  elementInserted: (function() {
    var $self = this.$("#message");
    $self.hide();
    $self.fadeIn(500);
  }).on('didInsertElement')
});
```

```html
<div id="message">
  {{flash.message}}
</div>
```

We use Scss, and have some conditional styling of the `background-color` based on the presence of `is-<type>` class. as in `is-error` would apply a red background.

the fade in works (obviously) however when inspecting in the console the exiting class is never applied to the `flash-message` component.

the code I hoped would work, again this is scss:

```scss
  #message {
    background-color: $color-notice;
    color: #fff;
    opacity: 1.0;
    font-size: 1em;
    line-height: 1.2em;
    padding: 1em;
    text-align: center;

    &.exiting {
      opacity: 0.0;
      transition: opacity .5s ease-in-out;
      -moz-transition: opacity .5s ease-in-out;
      -webkit-transition: opacity .5s ease-in-out;
    }
  }
```
