### ISSUE TITLE
CircleCI 1.0 no longer supported after August 31

### ISSUE THREAD

**Issue by bgentry** [poteto/ember-cli-flash#275]
While looking at [the tests](https://circleci.com/gh/poteto/ember-cli-flash/475) for #274, I noticed this warning from CircleCI:

<img width="1029" alt="screen shot 2018-07-17 at 6 24 52 pm" src="https://user-images.githubusercontent.com/114033/42854054-d3c3c9be-89ee-11e8-9ec6-b86899985af8.png">

> This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. **Please start migrating this project to CircleCI 2.0.**

Presumably this addon needs to be migrated to either Circle v2 or Travis by that date.

**Comment by Dhaulagiri** [comment]
The circle docs are painful so if anybody has an example of an ember app running with circle 2.0 that would be super helpful

**Comment by bgentry** [comment]
Here's the `.circleci/config.yml` from my own project:

```yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
        environment:
            NODE_ENV: test

    working_directory: ~/myapp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Printing Chrome version
          command: google-chrome --version

      - run:
          name: Yarn Install
          command: yarn install --non-interactive
      - run: yarn global add bower
      - run: ~/.yarn/bin/bower install

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - bower_components
            - .npm
            - .yarn-cache
            - .cache

      - run:
          name: Yarn Lint JS
          command: yarn run lint:js

      - run:
          name: Yarn Build
          command: yarn build-test

      - run:
          name: Yarn Test
          command: yarn test
```

Not doing any ember-try stuff there though. My recommendation for lowest pain / maintenance burden as an addon author is to just switch it to Travis since that works out-of-the-box w/ Ember.
